### ISSUE TITLE
Sonic pad getting root. 

### ISSUE THREAD

**Issue by nmoshier26** [smwoodward/Sonic-Pad-Updates#1]
Hello, I am using putty, whenever I try to SSH into it w/ creality:creality it denies access.

**Comment by Nskey** [comment]
Hello, 
Try
root:creality or
root:cxsw-sonic_2023

**Comment by nmoshier26** [comment]
I will try, thank you.

**Comment by nmoshier26** [comment]
Okay, I got in. But where can I find commands to access files?

**Comment by Nskey** [comment]
you can type
ls # To see the files and maps.  
cd ../ # You go back in the root map.
cd (mapname) to go the map.
vi  # are you using changes or create files.

**Comment by nmoshier26** [comment]
Okay, thank you.
